# -*- coding: utf-8 -*-
"""SVMGender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1edveTkxkuVLMMkko9I324_Z5RJbhywyX
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import torch

loan=pd.read_csv("/content/loan_data_set.csv")

loan.head()

for n,v in loan.items():
    if v.dtype == "object":
        loan[n] = v.factorize()[0]

# Fill missing values with mean column values in the train set
loan.fillna(loan.mean(), inplace=True)

Cols = ['Loan_ID',	'Married',	'Dependents',	'Education',	'Self_Employed',	'ApplicantIncome',	'CoapplicantIncome',	'LoanAmount',	'Loan_Amount_Term',	'Credit_History',	'Property_Area', 'Loan_Status']
X_cols = loan[Cols] # Features
Y_cols = loan.Gender
print(loan.Gender)

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X_cols, Y_cols, test_size=0.25) # 75% training and 25% test

#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel
#clf = svm.SVC(kernel='poly', degree=2) 
#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

from sklearn import metrics
from sklearn.metrics import accuracy_score, recall_score, classification_report

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average = 'macro')
print('F1 score: %f' % f1)

print(classification_report(y_test, y_pred))

from  imblearn.over_sampling import SMOTE

seed = 100
k = 3

sm = SMOTE(sampling_strategy='auto', k_neighbors=k, random_state=seed)
X_res, y_res = sm.fit_resample(X_train, y_train)

#Create a svm Classifier
clf2 = svm.SVC(kernel='linear') # Linear Kernel
#clf = svm.SVC(kernel='poly', degree=2) 
#Train the model using the training sets
clf2.fit(X_res, y_res)

#Predict the response for test dataset
y_pred = clf2.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average = 'macro')
print('F1 score: %f' % f1)

print(classification_report(y_test, y_pred))

